### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by acheong08** [arkadiyt/protodump#7]
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xabb332e]

goroutine 1 [running]:
github.com/arkadiyt/protodump/pkg/protodump.(*ProtoDefinition).writeField(0xc000076820, {0xac6b040, 0xc02ea1d418})
	/Users/yucheong/go/pkg/mod/github.com/arkadiyt/protodump@v0.0.0-20240316185756-5a6bdfec2205/pkg/protodump/proto.go:144 +0xb6e
github.com/arkadiyt/protodump/pkg/protodump.(*ProtoDefinition).writeMessage(0xc000076820, {0xac6a660, 0xc0001233c8})
	/Users/yucheong/go/pkg/mod/github.com/arkadiyt/protodump@v0.0.0-20240316185756-5a6bdfec2205/pkg/protodump/proto.go:217 +0xcc5
github.com/arkadiyt/protodump/pkg/protodump.(*ProtoDefinition).writeFileDescriptor(0xc000076820)
	/Users/yucheong/go/pkg/mod/github.com/arkadiyt/protodump@v0.0.0-20240316185756-5a6bdfec2205/pkg/protodump/proto.go:329 +0x785
github.com/arkadiyt/protodump/pkg/protodump.NewFromDescriptor(0xc02e92f200)
	/Users/yucheong/go/pkg/mod/github.com/arkadiyt/protodump@v0.0.0-20240316185756-5a6bdfec2205/pkg/protodump/proto.go:360 +0x10f
github.com/arkadiyt/protodump/pkg/protodump.NewFromBytes({0xc0170692a0, 0x16db, 0x16e2ed61})
	/Users/yucheong/go/pkg/mod/github.com/arkadiyt/protodump@v0.0.0-20240316185756-5a6bdfec2205/pkg/protodump/proto.go:344 +0xa5
main.main()
	/Users/yucheong/go/pkg/mod/github.com/arkadiyt/protodump@v0.0.0-20240316185756-5a6bdfec2205/cmd/protodump/main.go:46 +0x271
```

**Comment by arkadiyt** [comment]
@acheong08 can you please share the file that produces this behavior?

**Comment by arkadiyt** [comment]
I pushed up a change that I think will fix it - can you give it a try?

Unfortunately I wasn't able to figure out a proto definition file that could generate this behavior to confirm

**Comment by acheong08** [comment]
That fixed it. Thank you.
